### ISSUE TITLE
Lack of Station Records Consoles

### ISSUE THREAD

**Issue by VMSolidus** [DeltaV-Station/Delta-v-Legacy#113]
## Description

Forensic Mantis requires access to Station Records Consoles in order to properly do their job. Nearly every map in rotation does not have a SRC. The few that do have one, have it on the bridge where Mantis can't reach it.

**Comment by DebugOk** [comment]
Nyano issue, we won't make changes to upstream maps here. Best we can do is probably add a migration to turn that useless console into station records, but that'd have other side effects

**Comment by VMSolidus** [comment]
Do you have a link to the upstream github where I can make such a request, and/or PR it myself?

**Comment by IamVelcroboy** [comment]
There's a PR in the pipeline already that adds them to my maps. I'd ping Colin about theirs and, Ovni/Pebble are kinda wildcards.

**Comment by DebugOk** [comment]
> There's a PR in the pipeline already that adds them to my maps. I'd ping Colin about theirs and, Ovni/Pebble are kinda wildcards. 

Ovni is about to be removed from rotation on Delta when the new map gets in

**Comment by Colin-Tel** [comment]
https://github.com/Nyanotrasen/Nyanotrasen/pull/1766

I actually just added them to Angle and Shoukou in this PR on Nyano.
