### ISSUE TITLE
Taco Tuesday is postponed

### ISSUE THREAD

**Issue by Nuggles1** [DeltaV-Station/Delta-v-Legacy#205]
## Description
Taco recipe does not function as it's written. Just cooks dough into bread and leaves other ingredients raw.

**Reproduction**
Follow the recipe on the wiki. Dough, cheese wedge, tomato, two onion slices, and a raw cutlet. 10 sec in microwave.

**Comment by FluffiestFloof** [comment]
Recipe works correctly ingame, wiki had wrong info. Use a dough slice instead of dough.
Fixed on wiki.

https://github.com/DeltaV-Station/Delta-v/blob/fb9eaeb7e888f135f53924ffaab4bca318c97f9a/Resources/Prototypes/Recipes/Cooking/meal_recipes.yml#L1645-L1655

**Comment by Nuggles1** [comment]
Alright, I figured the fix was that simple. Cheers!
