### ISSUE TITLE
Psychologist cannot be selected in the character role menu

### ISSUE THREAD

**Issue by Anikyte** [DeltaV-Station/Delta-v-Legacy#41]
## Description
Psychologist can't be prioritized in the character creation job menu, but is still playable in game by joining mid round.

**Reproduction**
On the lobby screen, edit your character and go to job priorities. Psychologist is not in the list.

**Comment by FluffiestFloof** [comment]
Not a bug. They are wild cards and meant to be late join only.
At least that's how it was explained for those role last time I checked.
Reporter, Psychologist, Valet, Cataloguer are all considered wild cards late join roles.

**Comment by DebugOk** [comment]
Yeah, I think its intended to be like that
